[profile.default]
src = 'contracts'
out = 'out'
libs = ['node_modules', 'lib']
auto_detect_remappings = true
test = 'test/foundry'
cache_path  = 'cache_forge'
optimizer = true
optimizer_runs = 20_000
via_ir = true
names = true

[rpc_endpoints]
lisk-sepolia = "${LISK_SEPOLIA_RPC_URL}"
sepolia = "${SEPOLIA_RPC_URL}"

[etherscan]
lisk-sepolia = { key = "${ETHERSCAN_API_KEY}" }

[fmt]

[fuzz]

[invariant]
